### ISSUE TITLE
Clarifying the readme

### ISSUE THREAD

**Issue by codehag** [tc39/proposal-extractors#13]
Can you make it clear what `Foo` is in the readme? right now it is difficult to understand with no context what it is doing. Understanding it from the later examples is also difficult. A trivial implementation of `Foo` for each case, or even outputs and clear inputs, would help with understanding.

**Comment by rbuckton** [comment]
Ah, my apologies. I believe you are referring to [these examples](https://github.com/tc39/proposal-extractors#extractor-destructuring).   can definitely add additional example text for these.
