### ISSUE TITLE
Add example for if / while let bindings

### ISSUE THREAD

**Issue by MaxGraey** [tc39/proposal-extractors#5]
Firstly, thanks for the great proposal! 
In addition to more proper usage for Pattern Matching, it would be nice to add usage examples for "if let" binding as well.
It related to another abandoned proposal: https://github.com/tc39/proposal-Declarations-in-Conditionals
which may become new life with combining with extractors.
```ts
if (let Binary{ lhs, rhs } = expr) { // will not throw exception when failure!
   // use lhs, rhs if `expr instanceof Binary` 
}
```
Which more or less equivalent to:
```ts
if (expr instanceof Binary) {
   let { lhs, rhs } = expr;
   // use lhs, rhs
}
```

**Comment by rbuckton** [comment]
This is something that is covered by the [Pattern Matching](https://github.com/tc39/proposal-pattern-matching) proposal as something like:

```js
if (expr is Binary({ let lhs, let rhs })) {
  // use lhs, rhs
}
```
