### ISSUE TITLE
[] for array bindings instead of ()?

### ISSUE THREAD

**Issue by tolmasky** [tc39/proposal-extractors#8]
I'm just curious why () was chosen instead of [] for array binding patterns:

```javascript
Foo[y] = x;
```

vs.

```javascript
Foo(y) = x;
```

**Comment by rbuckton** [comment]
> I'm just curious why () was chosen instead of [] for array binding patterns:
> 
> ```js
> Foo[y] = x;
> ```
> 
> vs.
> 
> ```js
> Foo(y) = x;
> ```

The syntax `Foo[y] = x` is already valid and meaningful JavaScript and thus can't be used for this. `()` was chosen because a call expression isn't a valid assignment target and will always throw when assigned to today.
