### ISSUE TITLE
Can this be an extension of decorators instead?

### ISSUE THREAD

**Issue by trusktr** [tc39/proposal-extractors#9]
```js
let @Foo x = y
```

or similar, leaving the implementation to decorator authors (perhaps also providing decorator primitives for authors to use)?

**Comment by rbuckton** [comment]
No, decorators are intended to be declarative and apply only once during declaration instantiation. Extractors are intended to be evaluated as part of normal evaluation, such as during any function call or during each successive iteration of a `for` loop. 

For example,
```js
class C {
  m(@Foo x) { }
}
```
would run once when `C` is defined, and could be used to describe metadata about the `x` parameter of `C`'s `m` method.

However,
```js
class C {
  m(Foo(x, y)) { }
}
```
would run every type `m` is called as part of destructuring the first argument.
